version: '3.8'

services:
  resumatch-dev:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "8001:8001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - FLASK_PORT=8001
      - LOG_LEVEL=DEBUG
    env_file:
      - env.development
    volumes:
      - .:/app
      - ./uploads_dev:/app/uploads_dev
      - ./logs_dev:/app/logs_dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  # Development Redis for caching
  redis-dev:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

  # Development PostgreSQL for analytics
  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: resumatch_dev
      POSTGRES_USER: resumatch_dev
      POSTGRES_PASSWORD: resumatch_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # Jupyter notebook for development
  jupyter-dev:
    image: jupyter/minimal-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

volumes:
  redis_dev_data:
  postgres_dev_data:
